hostName = "basalt-pi-4"
[wireless]
enable = true
interfaces = [ "wlan0" ]

# replace "SSID" and "PSK" with real values
[networks."SSID"]
psk = "PSK"
priority = 10

# [ap]
# enable = false
# internet_interface = "wlan0"
# wifi_interface = "wlp1s0u1"
# ssid = "SSID"
# psk = "PSK"
